# Database credentials
database:
  # antingen denna
  file: "database/sqlite" 
  # eller alla dessa (om file är blankt)
  sql-user: ""            #
  sql-pass: ""
  sql-server: "127.0.0.1"
  sql-database: "SupportSystem"
  sql-port: 3306

redis:
  server: "localhost:6379"

sso:
  clientId:  "StudentPortal"
  clientSecret:  "EM4WKTSRUXVWG5RBTXC3VPOBTMF5Y3SL"
  baseAddress:  "https://localhost:44375/"
  backBaseAddress: "https://localhost:8080/"

s3:
  aws_key: "e74f3ebd16517acd6cf2ce145af234aef5bab39b"
  aws_secret: "KYgM66sbxu6RbKYZGs+IYukSYLdZdJJmJS9w7vwzuqk="
  s3_host_base: "axmjqhyyjpat.compat.objectstorage.eu-amsterdam-1.oraclecloud.com"
  urlgenerator: "https://objectstorage.eu-amsterdam-1.oraclecloud.com/n/axmjqhyyjpat/b/<BUCKETNAME>/o/<FILENAME>"
  bucket: "aspcodeprod-aspcodeprod"
