# Database credentials
database:
  # antingen denna
  file: "" 
  # eller alla dessa (om file är blankt)
  sql-user: "root"            #
  sql-pass: "my-secret-pw"
  sql-server: "127.0.0.1"
  sql-database: "Salary"
  sql-port: 3307

redis:
  server: "localhost:6379"

sso:
  clientId:  "StudentPortal"
  clientSecret:  "EM4WKTSRUXVWG5RBTXC3VPOBTMF5Y3SL"
  baseAddress:  "https://localhost:44375/"
  backBaseAddress: "https://localhost:8080/"


s3:
  aws_key: "e74f3ebd16517acd6cf2ce145af234aef5bab39b"
  aws_secret: "KYgM66sbxu6RbKYZGs+IYukSYLdZdJJmJS9w7vwzuqk="
  s3_host_base: "axmjqhyyjpat.compat.objectstorage.eu-amsterdam-1.oraclecloud.com"
  urlgenerator: "https://objectstorage.eu-amsterdam-1.oraclecloud.com/n/axmjqhyyjpat/b/aspcodeprod-aspcodeprod/o/"
  bucket: "aspcodeprod-aspcodeprod"
